name: Deploy to AWS S3
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v1
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy static site to S3 bucket
        run: aws s3 sync . s3://abcghsdhg --delete
      - name: Create ECS Cluster
        run: |
          aws ecs create-cluster --cluster-name nginx-cluster
     # Step to register task definition
      - name: Register Task Definition
        run: |
          aws ecs register-task-definition \
            --family nginx-task \
            --container-definitions '[{"name":"abc","image":"905418310808.dkr.ecr.us-east-2.amazonaws.com/abc:github.sha","portMappings":[{"containerPort":80}],"memoryReservation":128}]'
     # Step to create ECS service
      - name: Create ECS Service
        run: |
          aws ecs create-service \
            --cluster nginx-cluster \
            --service-name nginx-service \
            --task-definition nginx-task \
            --desired-count 1 \
            --launch-type EC2 \
            --region ${{ env.AWS_REGION }}
